-- SCRIPT PARA CRIAÇÃO DO BANCO DE DADOS --
-- -- -- -- -- -- -- -- -- -- -- OFICINA --

-- DROP DATABASE OFICINA;
CREATE DATABASE OFICINA;
USE OFICINA;

CREATE TABLE MECANICOS (
    ID_MECANICO INT AUTO_INCREMENT PRIMARY KEY,
    CPF CHAR(11) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    ESPECIALIZACAO ENUM('MECANICA','SUSPENSAO','VIDRO','ELETRICA','HIDRAULICA','OUTRA') DEFAULT 'MECANICA',
    TURNO_TRABALHO ENUM('M','T','M/T') NOT NULL DEFAULT 'M/T',
    VALOR_HORA FLOAT NOT NULL,
    CONSTRAINT UNIQUE_CPF_MECANICO UNIQUE (CPF)
);

ALTER TABLE MECANICOS AUTO_INCREMENT = 1;

CREATE TABLE PECAS (
    ID_PECA INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PECA VARCHAR(100) NOT NULL,
    CODIGO_PECA VARCHAR(45) NOT NULL,
    QUANTIDADE_ESTOQUE INT,
    PRECO FLOAT,
    CONSTRAINT CODIGO_PECA_UNICO UNIQUE (CODIGO_PECA)
);

ALTER TABLE PECAS AUTO_INCREMENT = 1;

CREATE TABLE CLIENTES (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    ENDERECO VARCHAR(200) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(45),
    DATA_NASCIMENTO DATE
);

ALTER TABLE CLIENTES AUTO_INCREMENT = 1;

CREATE TABLE VEICULOS (
    ID_VEICULO INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    MARCA VARCHAR(45) NOT NULL,
    MODELO VARCHAR(45) NOT NULL,
    COR VARCHAR(45),
    ANO_FABRICACAO INT(4),
    PLACA VARCHAR(15) NOT NULL,
    CONSTRAINT FK_VEICULOS_CLIENTES FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
    CONSTRAINT PLACA_UNICA UNIQUE (PLACA)
);

ALTER TABLE VEICULOS AUTO_INCREMENT = 1;

CREATE TABLE ORDENS_SERVICO (
    ID_ORDEM INT AUTO_INCREMENT PRIMARY KEY,
    ID_VEICULO INT,
    DATA_ABERTURA DATE NOT NULL,
    DATA_CONCLUSAO_ESTIMADA DATE,
    DATA_FINALIZACAO DATE,
		DESC_PROBLEMA VARCHAR(255),
		VALOR_ESTIMADO FLOAT,
    STATUS ENUM('EM AVALIACAO', 'EM MANUTENCAO', 'FINALIZADO') NOT NULL DEFAULT 'EM MANUTENCAO',
    CONSTRAINT FK_ORD_SERVICO_VEICULOS FOREIGN KEY (ID_VEICULO) REFERENCES VEICULOS(ID_VEICULO)
);

ALTER TABLE ORDENS_SERVICO AUTO_INCREMENT = 1;

CREATE TABLE LISTA_SERVICOS (
		ID_SERVICO INT AUTO_INCREMENT PRIMARY KEY,
		NOME_SERVICO VARCHAR(100) NOT NULL,
		PRECO FLOAT NOT NULL,
		TEMPO_ESTIMADO_HS FLOAT NOT NULL
);

ALTER TABLE LISTA_SERVICOS AUTO_INCREMENT = 1;

CREATE TABLE EXECUCAO (
		ID_EXECUCAO INT AUTO_INCREMENT PRIMARY KEY,
    ID_ORDEM INT,
    DESC_SERVICO VARCHAR(255) NOT NULL,
    PRECO FLOAT, -- PODE SER ATRIBUIDO UM VALOR TOTAL, OU CALCULADO POR MEIO DOS PRECOS DE PECAS E SERVICOS LISTADOS
    CONSTRAINT FK_EXECUCAO_ORD_SERVICO FOREIGN KEY (ID_ORDEM) REFERENCES ORDENS_SERVICO(ID_ORDEM)
);

ALTER TABLE EXECUCAO AUTO_INCREMENT = 1;

CREATE TABLE MECANICOS_EXECUCAO (
		ID_MECANICO INT,
    ID_EXECUCAO INT,
    CONSTRAINT FK_MECANICO_EXECUCAO_1 FOREIGN KEY (ID_MECANICO) REFERENCES MECANICOS(ID_MECANICO),
    CONSTRAINT FK_MECANICO_EXECUCAO_2 FOREIGN KEY (ID_EXECUCAO) REFERENCES EXECUCAO(ID_EXECUCAO)
);

CREATE TABLE PECAS_EXECUCAO (
		ID_PECA INT,
    ID_EXECUCAO INT,
    QUANTIDADE INT,
    CONSTRAINT FK_PECAS_EXECUCAO_1 FOREIGN KEY (ID_PECA) REFERENCES PECAS(ID_PECA),
    CONSTRAINT FK_PECAS_EXECUCAO_2 FOREIGN KEY (ID_EXECUCAO) REFERENCES EXECUCAO(ID_EXECUCAO)
);

CREATE TABLE SERVICOS_EXECUCAO (
		ID_SERVICO INT,
		ID_EXECUCAO INT,
		CONSTRAINT FK_SERVICO_EXECUCAO_1 FOREIGN KEY (ID_SERVICO) REFERENCES LISTA_SERVICOS(ID_SERVICO),
		CONSTRAINT FK_SERVICO_EXECUCAO_2 FOREIGN KEY (ID_EXECUCAO) REFERENCES EXECUCAO(ID_EXECUCAO)
);
