--  RESPONDENDO PERGUNTAS COM QUERIES SQL --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- --

USE OFICINA;
SHOW TABLES;

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- RECUPERANDO DADOS DE QUAIS SERVICOS CADA MECANICO EXECUTOU
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
SELECT
    NOME AS MECÂNICO,
    ESPECIALIZACAO,
    DESC_SERVICO
FROM EXECUCAO E
	INNER JOIN MECANICOS_EXECUCAO ME ON E.ID_EXECUCAO = ME.ID_EXECUCAO
    INNER JOIN MECANICOS M ON ME.ID_MECANICO = M.ID_MECANICO;

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- RECUPERANDO DADOS DE QUANTOS SERVICOS CADA MECANICO EXECUTOU ORDENADO POR QUANTIDADE
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
SELECT
	M.NOME,
	COUNT(*) AS QTD_EXECUCOES
FROM EXECUCAO E
	INNER JOIN MECANICOS_EXECUCAO ME ON E.ID_EXECUCAO = ME.ID_EXECUCAO
    INNER JOIN MECANICOS M ON ME.ID_MECANICO = M.ID_MECANICO
GROUP BY M.NOME
ORDER BY QTD_EXECUCOES DESC;

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- RECUPERANDO DADOS DE QUAL CLIENTE ABRIU MAIS ORDENS DE SERVICO
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
SELECT
	C.NOME,
	COUNT(*) AS QTD_ATENDIMENTOS
FROM CLIENTES C
	INNER JOIN VEICULOS VE ON C.ID_CLIENTE = VE.ID_CLIENTE
    INNER JOIN ORDENS_SERVICO O ON VE.ID_VEICULO = O.ID_VEICULO
GROUP BY C.NOME
ORDER BY QTD_ATENDIMENTOS DESC;

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- RECUPERANDO DADOS DE QUAL CLASSIFICAÇÃO DE SERVIÇO É MAIS EXECUTADO
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
SELECT
	L.NOME_SERVICO,
    COUNT(*) AS QTD_SERVICOS
FROM EXECUCAO E
	INNER JOIN SERVICOS_EXECUCAO SE ON E.ID_EXECUCAO = SE.ID_EXECUCAO
    INNER JOIN LISTA_SERVICOS L ON SE.ID_SERVICO = L.ID_SERVICO
GROUP BY L.NOME_SERVICO
ORDER BY QTD_SERVICOS DESC;

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- RECUPERANDO DADOS DE DIFERENÇAS PERCENTUAIS ENTRE VALOR ESTIMADO DA ORDEM DE SERVICO
-- E O VALOR EFETIVAMENTE PAGO NA EXECUCAO DO SERVICO - ORDENADO PELA DESCRIÇÃO DO PROBLEMA
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
SELECT
    O.ID_VEICULO,
    E.DESC_SERVICO,
    (E.PRECO - O.VALOR_ESTIMADO) AS DIFERENCA_VALORES,
	CASE
		WHEN E.PRECO  > 1.50 * O.VALOR_ESTIMADO THEN 'ACIMA DE 50% MAIS CARO QUE VALOR ESTIMADO'
        WHEN E.PRECO  > 1.20 * O.VALOR_ESTIMADO THEN 'ACIMA DE 20% MAIS CARO QUE VALOR ESTIMADO'
		WHEN E.PRECO  > 1.10 * O.VALOR_ESTIMADO THEN 'ACIMA DE 10% MAIS CARO QUE VALOR ESTIMADO'
			WHEN E.PRECO  <= 1.10 * O.VALOR_ESTIMADO
            AND E.PRECO >= 0.90 * O.VALOR_ESTIMADO THEN 'CORRESPONDE AO ESTIMADO'
		WHEN E.PRECO < 0.90 * O.VALOR_ESTIMADO THEN 'ABAIXO DE 10% MAIS BARATO QUE VALOR ESTIMADO'
    END AS DIFERENCA_PERCENTUAL
FROM ORDENS_SERVICO O
INNER JOIN EXECUCAO E ON O.ID_ORDEM = E.ID_ORDEM
ORDER BY O.DESC_PROBLEMA;

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- RECUPERANDO QUAIS PECAS E SUAS QUANTIDADES UTILIZADAS POR CARRO, ORDENADO POR MARCA DO CARRO
-- POR MEIO DO ID DO VEICULO E POSSIVEL DIFERENCIAR ENTRE CARROS DIFERENTES
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
SELECT
	V.ID_VEICULO,
    V.MARCA,
    V.MODELO,
    P.NOME_PECA,
    PE.QUANTIDADE AS QTD_UTILIZADA
FROM VEICULOS AS V
	INNER JOIN ORDENS_SERVICO AS O ON V.ID_VEICULO = O.ID_VEICULO
    INNER JOIN EXECUCAO AS E ON O.ID_ORDEM = E.ID_ORDEM
    INNER JOIN PECAS_EXECUCAO AS PE ON E.ID_EXECUCAO = PE.ID_EXECUCAO
    INNER JOIN PECAS AS P ON PE.ID_PECA = P.ID_PECA
ORDER BY MARCA;

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- RECUPERANDO QUAIS MODELOS DE MOTOR ABREM MAIS ORDENS DE SERVICO
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
SELECT
	V.MODELO,
    COUNT(*) AS QTD_ORDENS
FROM VEICULOS AS V
	INNER JOIN ORDENS_SERVICO AS O ON V.ID_VEICULO = O.ID_VEICULO
    INNER JOIN EXECUCAO AS E ON O.ID_ORDEM = E.ID_ORDEM
    INNER JOIN PECAS_EXECUCAO AS PE ON E.ID_EXECUCAO = PE.ID_EXECUCAO
    INNER JOIN PECAS AS P ON PE.ID_PECA = P.ID_PECA
GROUP BY V.MODELO
ORDER BY QTD_ORDENS DESC;